In [2]:
#16강

import numpy as np
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

ar1 = np.array([1, 2, 3, 4])
ar2 = np.array([5, 6, 7, 8])
ar1
ar2

array([1, 2, 3, 4])

array([5, 6, 7, 8])

In [8]:
ar1 = np.array([1.1, 2, 3, 100])
ar1
type(ar1)
ar1.dtype
ar1.shape
ar1.ndim
ar1.size
ar1.nbytes

array([  1.1,   2. ,   3. , 100. ])

numpy.ndarray

dtype('float64')

(4,)

1

4

32

In [19]:
ar1 = np.array([[6, 5, 4], [3, 2, 1]], np.int32)
ar1
ar1.shape
ar1.size
ar1.dtype
ar1.nbytes

array([[6, 5, 4],
       [3, 2, 1]])

(2, 3)

6

dtype('int32')

24

In [18]:
ar2 = np.array([[6, 5, 4], [3, 2, 1]], np.float16)
ar2
ar2.shape
ar2.size
ar2.dtype
ar2.nbytes

array([[6., 5., 4.],
       [3., 2., 1.]], dtype=float16)

(2, 3)

6

dtype('float16')

12

In [4]:
ar1 = np.array([1, 2, 3, 4], np.float16)
print(ar1.dtype)
ar1 = np.array([1, 2, 3, 4], np.float32)
print(ar1.dtype)
ar1 = np.array([1, 2, 3, 4], np.float64)
print(ar1.dtype)
ar1 = np.array([1, 2, 3, 4], float)
print(ar1.dtype)

float16
float32
float64
float64


In [25]:
ar1 = np.array([[1, 2, 3], [4, 5, 6]])
ar2 = ar1.reshape(-1, 2)
print(ar1)
print(ar2)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [29]:
#17강

v1 = np.array([1, 2, 3, 4, 5, 6])
print(v1.reshape(-1, 6))
print(v1.reshape(-1, 3))
print(v1.reshape(-1, 2))
print(v1.reshape(-1, 1))

[[1 2 3 4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [8]:
ar1 = np.arange(1, 61).reshape(5, 3, 4)
print(ar1)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]

 [[25 26 27 28]
  [29 30 31 32]
  [33 34 35 36]]

 [[37 38 39 40]
  [41 42 43 44]
  [45 46 47 48]]

 [[49 50 51 52]
  [53 54 55 56]
  [57 58 59 60]]]


In [9]:
ar2 = ar1.reshape(60,)
print(ar2)
ar3 = ar1.reshape(1, 60)
print(ar3)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60]
[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
  25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
  49 50 51 52 53 54 55 56 57 58 59 60]]


In [11]:
ar4 = ar2.reshape(-1, 10)
print(ar4)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]
 [51 52 53 54 55 56 57 58 59 60]]


In [37]:
ar1 = np.arange(15).reshape(3, 5)
ar1[1][3] = 1000
ar1

array([[   0,    1,    2,    3,    4],
       [   5,    6,    7, 1000,    9],
       [  10,   11,   12,   13,   14]])

In [13]:
ar1 = np.arange(60).reshape(6, 2, 5)
ar1[3, 0, 4] = 1000
ar1

array([[[   0,    1,    2,    3,    4],
        [   5,    6,    7,    8,    9]],

       [[  10,   11,   12,   13,   14],
        [  15,   16,   17,   18,   19]],

       [[  20,   21,   22,   23,   24],
        [  25,   26,   27,   28,   29]],

       [[  30,   31,   32,   33, 1000],
        [  35,   36,   37,   38,   39]],

       [[  40,   41,   42,   43,   44],
        [  45,   46,   47,   48,   49]],

       [[  50,   51,   52,   53,   54],
        [  55,   56,   57,   58,   59]]])

In [44]:
ar1 = np.arange(24).reshape(4, 6)
ar1[2:, 1:4] = np.array([[-1, -2, -3], [-4, -5, 6]])
ar1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, -1, -2, -3, 16, 17],
       [18, -4, -5,  6, 22, 23]])

In [15]:
ar1 = np.arange(24).reshape(2, 12)
ar1[:: , ::4]

array([[ 0,  4,  8],
       [12, 16, 20]])

In [64]:
ar1 = np.zeros((4, 4), np.int8)
ar1[1, ::] = 2
ar1[::, 2] = 4
ar1

array([[0, 0, 4, 0],
       [2, 2, 4, 2],
       [0, 0, 4, 0],
       [0, 0, 4, 0]], dtype=int8)

In [68]:
ar1 = np.random.uniform(0, 2, size = (3, 5))
ar1
ar1[::, [0, 2, 3]]

array([[0.29270801, 1.13471872, 0.75326321, 1.69434171, 0.33140591],
       [1.95599862, 0.30982692, 1.74280109, 0.11344632, 0.70907907],
       [1.29168357, 1.79730314, 1.8584274 , 0.90703797, 1.93828707]])

array([[0.29270801, 0.75326321, 1.69434171],
       [1.95599862, 1.74280109, 0.11344632],
       [1.29168357, 1.8584274 , 0.90703797]])

In [71]:
ar1 = np.random.randint(10, 15, size = (4, 2, 3))
ar1
ar1[1,:: , ::]

array([[[10, 13, 14],
        [14, 13, 13]],

       [[14, 10, 10],
        [10, 11, 11]],

       [[14, 12, 11],
        [13, 13, 11]],

       [[14, 11, 13],
        [12, 13, 10]]])

array([[14, 10, 10],
       [10, 11, 11]])

In [74]:
ar1 = np.random.choice(np.arange(6), size = (3), replace = False)
ar1

array([2, 5, 4])

In [22]:
#18강

ar1 = np.arange(0, 60, 3).reshape(4, 5)
ar1
ar1.sum()
ar1.sum(axis=1)
ar1.mean(axis=0)

array([[ 0,  3,  6,  9, 12],
       [15, 18, 21, 24, 27],
       [30, 33, 36, 39, 42],
       [45, 48, 51, 54, 57]])

570

array([ 30, 105, 180, 255])

array([22.5, 25.5, 28.5, 31.5, 34.5])

In [26]:
ar1 = np.random.randint(100, size=(4, 5))
ar1
ar1.argmax(axis=1).reshape(-1, 1)

array([[14, 82, 26, 41, 14],
       [ 8, 11, 39, 80,  3],
       [ 1, 13,  2,  1, 11],
       [ 6, 72, 27, 59, 38]])

array([[1],
       [3],
       [1],
       [1]], dtype=int64)

In [30]:
ar1 = np.arange(36).reshape(4, 9)
ar1
ar1[::, 2::3].mean(axis=0)
ar1[::, 2::3].std(axis=0)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

array([15.5, 18.5, 21.5])

array([10.0623059, 10.0623059, 10.0623059])

In [40]:
ar1 = np.random.randint(100, size=(3, 4, 5))
ar1
np.median(ar1, axis=2)
ar1.reshape(-1, 20).max(axis=1)

array([[[10,  6, 79, 49, 38],
        [23, 14, 94, 14, 79],
        [ 3, 88, 91, 98,  9],
        [50, 80, 33, 56,  4]],

       [[27, 23, 54, 50, 96],
        [66, 36, 11, 37, 57],
        [18, 71, 11, 15,  1],
        [67, 78, 23, 53, 97]],

       [[32, 79, 12, 29, 38],
        [38, 19, 46, 73, 80],
        [18, 54, 67, 69, 28],
        [13, 37,  0, 50, 28]]])

array([[38., 23., 88., 50.],
       [50., 37., 15., 67.],
       [32., 46., 54., 28.]])

array([98, 97, 80])

In [44]:
ar1 = np.arange(4, 41, 4)
ar2 = ar1 * ar1
ar2.sum()
ar1 * ar1.sum()
(ar1 * ar1).sum()

6160

array([ 880, 1760, 2640, 3520, 4400, 5280, 6160, 7040, 7920, 8800])

6160

In [3]:
ar1 = np.arange(0, 51, 5)
ar2 = ar1 % 3
ar2.sum()

result = 0
for i in range(0, 51, 5):
    result += (i % 3)
print(result)

11

11


In [62]:
ar1 = np.arange(15).reshape(3, 5)
ar1
ar2 = np.array([2, 3, 1]).reshape(-1, 1)
ar2
ar1 + ar2
ar3 = np.random.randint(10, size=(3)).reshape(-1, 1)
ar3
ar1 + ar3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

array([[2],
       [3],
       [1]])

array([[ 2,  3,  4,  5,  6],
       [ 8,  9, 10, 11, 12],
       [11, 12, 13, 14, 15]])

array([[6],
       [5],
       [6]])

array([[ 6,  7,  8,  9, 10],
       [10, 11, 12, 13, 14],
       [16, 17, 18, 19, 20]])

In [72]:
v1 = np.array([1, 2, 3]).reshape(1, 3)
v1
m2 = np.concatenate((v1, v1, v1), axis=0)
m2
m2 = np.concatenate((m2, v1.reshape(3, 1)), axis=1)
m2

array([[1, 2, 3]])

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

array([[1, 2, 3, 1],
       [1, 2, 3, 2],
       [1, 2, 3, 3]])

In [10]:
ar1 = np.random.randint(1, 6, size=(3, 4))
ar1
np.sqrt(ar1)
sum(np.sqrt(ar1).reshape(-1,))

array([[5, 1, 3, 5],
       [1, 1, 2, 1],
       [5, 1, 1, 3]])

array([[2.23606798, 1.        , 1.73205081, 2.23606798],
       [1.        , 1.        , 1.41421356, 1.        ],
       [2.23606798, 1.        , 1.        , 1.73205081]])

17.58651911001022

In [14]:
#19강

ar1 = np.random.randint(1, 6, size=(3, 4))
ar1
ar1.mean(axis=1)
ar1.std(axis=1)
ar2 = (ar1 - ar1.mean(axis=1).reshape(-1, 1)) / ar1.std(axis=1).reshape(-1, 1)
ar2

array([[1, 3, 5, 2],
       [2, 2, 3, 2],
       [4, 3, 5, 4]])

array([2.75, 2.25, 4.  ])

array([1.47901995, 0.4330127 , 0.70710678])

array([[-1.18321596,  0.16903085,  1.52127766, -0.50709255],
       [-0.57735027, -0.57735027,  1.73205081, -0.57735027],
       [ 0.        , -1.41421356,  1.41421356,  0.        ]])

In [27]:
ar1 = np.random.randint(1, 11, size=(3, 4))
ar1
ar1 % 3 == 0
np.sum(ar1 % 3 == 0)

array([[ 7,  4,  1,  6],
       [ 1,  1, 10,  6],
       [ 9,  1,  6,  6]])

array([[False, False, False,  True],
       [False, False, False,  True],
       [ True, False,  True,  True]])

5

In [26]:
ar1 = np.random.randint(1, 11, size=(3, 4))
ar1
ar1 % 3 == 0
(ar1 % 3 == 0).sum(axis=1)

array([[3, 1, 7, 8],
       [1, 7, 2, 3],
       [3, 3, 9, 9]])

array([[ True, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True]])

array([1, 1, 4])

In [30]:
a1 = np.arange(4, 41, 4)
a2 = a1 * a1
a2 % 6
np.sum(a2 % 6 == 0)

array([4, 4, 0, 4, 4, 0, 4, 4, 0, 4], dtype=int32)

3

In [31]:
a1 = np.random.randint(1, 11, size = (3, 3))
a1
a2 = a1!=6
a3 = a1 % 3 == 0
a4 = a2 & a3
a4.sum()

array([[ 2,  3,  4],
       [ 9,  4,  7],
       [10,  9,  2]])

3

In [9]:
a1 = np.random.randint(1, 11, size = (5, 5))
a1
a2 = np.where(a1 >= 7, a1, 0)
a2
a2.sum()
a1[a1 >= 7].sum()

array([[ 9,  9,  6,  4,  7],
       [10,  4,  6,  5,  3],
       [ 8, 10,  1,  8,  1],
       [ 4,  3,  3,  2,  2],
       [ 3,  1,  8,  3,  4]])

array([[ 9,  9,  0,  0,  7],
       [10,  0,  0,  0,  0],
       [ 8, 10,  0,  8,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  8,  0,  0]])

69

69

In [8]:
a1 = np.random.randint(1, 11, size = (5, 5))
a1
a2 = a1 >= 7
a3 = a1 % 2 == 0
a4 = np.where(a2&a3, a1, 0)
a4
a4.sum()
a1[a2&a3].sum()

array([[ 1, 10,  8,  4,  5],
       [ 5,  3,  9,  7,  1],
       [10,  9,  3,  1,  2],
       [ 1,  4,  7,  7,  7],
       [ 8,  4,  7,  6,  2]])

array([[ 0, 10,  8,  0,  0],
       [ 0,  0,  0,  0,  0],
       [10,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 8,  0,  0,  0,  0]])

36

36

In [58]:
a1 = np.arange(24).reshape(6, 4)
a1
b1 = a1[:, 3]
a2 = b1 % 3 == 0
b1[a2]
a3 = b1 > 10
b1[a3]
np.sum(np.where(a2 | a3, b1, 0))
b1[a2 | a3].sum()

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

array([ 3, 15])

array([11, 15, 19, 23])

71

71

In [77]:
a1 = np.random.randint(10, size=(5, 5))
a1
b1 = a1[:, 4]
b1
b2 = b1 > 5
b2
a1[b2].mean(axis=1)

array([[7, 7, 8, 5, 0],
       [0, 8, 0, 2, 0],
       [3, 2, 4, 4, 5],
       [9, 5, 0, 9, 7],
       [3, 3, 9, 9, 8]])

array([0, 0, 5, 7, 8])

array([False, False, False,  True,  True])

array([6. , 6.4])

In [89]:
math = np.random.randint(10, size=10)
math
engl = np.random.randint(10, size=10)
engl
a1 = math < engl
a1
a1.sum()
math[a1]
np.around(math[a1].mean(), 3)

array([1, 0, 2, 3, 0, 7, 8, 9, 2, 9])

array([6, 6, 7, 9, 5, 4, 0, 6, 6, 5])

array([ True,  True,  True,  True,  True, False, False, False,  True,
       False])

6

array([1, 0, 2, 3, 0, 2])

1.333

In [6]:
#20강

a1 = np.random.randint(100, size=(4, 5))
a1
b1 = np.where(a1 > 70)
b1
type(b1)
##fancy index O
l1 = a1[b1]
l1
type(l1)
##fancy index X
l2 = []
for ii, jj in zip(b1[0], b1[1]):
    l2.append(a1[ii, jj])
l2
type(l2)

array([[59, 32,  1, 12, 22],
       [31, 51, 40, 39, 91],
       [54, 17, 96, 95, 15],
       [87,  5, 88, 66, 87]])

(array([1, 2, 2, 3, 3, 3], dtype=int64),
 array([4, 2, 3, 0, 2, 4], dtype=int64))

tuple

array([91, 96, 95, 87, 88, 87])

numpy.ndarray

[91, 96, 95, 87, 88, 87]

list

In [16]:
menu = np.array([1000, 2000, 1500, 2000])
order = np.array([1, 1, 3, 2, 2, 3, 4, 1])
np.sum(menu[order - 1])

12000

In [26]:
a1 = np.random.randint(10, size=(6, 4))
a1 = a1.astype(float)
a1[[0, 1, 1, 3], [1, 1, 2, 3]] = np.nan
a1
b1 = ~np.isnan(a1)

a1[~np.isnan(a1).any(axis=1)]
#any 안 쓰고 하는 법 교수님께 질문

array([[ 3., nan,  2.,  0.],
       [ 3., nan, nan,  4.],
       [ 9.,  8.,  1.,  4.],
       [ 4.,  2.,  0., nan],
       [ 5.,  5.,  3.,  0.],
       [ 1.,  8.,  7.,  6.]])

array([[ True, False,  True,  True],
       [ True, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

array([[9., 8., 1., 4.],
       [5., 5., 3., 0.],
       [1., 8., 7., 6.]])

In [31]:
a1 = np.random.randint(100, size=(5, 10))
np.savetxt(fname='file1_int.txt', X=a1, fmt='%d', delimiter='\t')
a2 = np.random.randint(0, 3, size=(5, 10))
np.savetxt(fname='file2_float.txt', X=a2, fmt='%.3f', delimiter=',')
a3 = np.random.randint(100, size=(5, 10))
a3 = a3.astype(float)
a3[[1, 2], [1, 2]] = np.nan
a3
np.savetxt(fname='file3_nan.txt', X=a3, fmt='%.3f', delimiter='\t')

array([[41., 90., 17., 72.,  1., 94., 56., 93., 24., 89.],
       [59., nan, 84., 29., 85., 56., 13., 51., 53., 51.],
       [68., 99., nan, 57., 48., 36., 24., 69., 96., 83.],
       [57., 32., 73., 33., 77., 29., 83., 63., 67., 31.],
       [79., 37., 15., 63., 38., 90., 29., 86.,  9., 67.]])

In [42]:
np.loadtxt(fname='file2_float.txt', dtype=float, delimiter=',')
np.loadtxt(fname='file2_float.txt', dtype=float, delimiter=',', max_rows=2)
np.loadtxt(fname='file2_float.txt', dtype=float, delimiter=',', usecols=[0, 1, 2])

array([[1., 2., 2., 0., 1., 0., 1., 2., 1., 1.],
       [1., 2., 2., 1., 2., 2., 0., 1., 1., 0.],
       [0., 0., 0., 2., 0., 1., 0., 0., 0., 2.],
       [2., 1., 2., 1., 1., 1., 2., 0., 2., 1.],
       [0., 0., 0., 0., 1., 1., 2., 1., 2., 0.]])

array([[1., 2., 2., 0., 1., 0., 1., 2., 1., 1.],
       [1., 2., 2., 1., 2., 2., 0., 1., 1., 0.]])

array([[1., 2., 2.],
       [1., 2., 2.],
       [0., 0., 0.],
       [2., 1., 2.],
       [0., 0., 0.]])

In [43]:
a1 = np.loadtxt(fname='file3_nan.txt', dtype=float, delimiter='\t')
a1
np.isnan(a1).sum()

array([[41., 90., 17., 72.,  1., 94., 56., 93., 24., 89.],
       [59., nan, 84., 29., 85., 56., 13., 51., 53., 51.],
       [68., 99., nan, 57., 48., 36., 24., 69., 96., 83.],
       [57., 32., 73., 33., 77., 29., 83., 63., 67., 31.],
       [79., 37., 15., 63., 38., 90., 29., 86.,  9., 67.]])

2

In [7]:
a1 = np.loadtxt(fname='file1_int.txt', dtype=int, delimiter='\t')
a1
a1.mean(axis=1)
a1[a1 > 50].mean()

array([[ 4, 58, 63, 60, 33, 28, 83, 70, 46, 64],
       [82, 42, 77, 95, 41, 18, 22, 18, 40, 66],
       [32, 16, 47, 55, 96, 59, 79, 27, 25, 40],
       [52, 24, 58, 13, 50, 81, 88, 61, 14, 22],
       [34, 59, 64,  6, 91, 22, 83, 11, 72, 89]])

array([50.9, 50.1, 47.6, 46.3, 53.1])

72.2

In [9]:
a4 = np.random.uniform(-5, 6, size=(5, 10))
a4 = np.round(a4, 3)
a4 = a4.astype(str)
a4[[0, 1, 3], [1, 1, 2]] = ' '
np.savetxt(fname='file4_blank.txt', X=a4, fmt = '%s', delimiter='\t')

In [33]:
#지수표현 없애주고 출력하는 자리수 세팅
np.set_printoptions(precision=3, suppress=True)
a1 = np.genfromtxt(fname='file4_blank.txt', dtype=float, delimiter='\t')
print(a1)
a2 = a1[~np.isnan(a1).any(axis=1)]
np.max(a2, axis=1)
np.argmax(a2, axis=1)

[[-1.267    nan  1.937 -1.083 -2.726  5.236  0.83   4.516 -1.071 -1.199]
 [ 5.802    nan  4.759 -2.585 -2.294  2.125 -0.016  4.871  3.66  -4.876]
 [-1.05  -4.923  4.042 -3.467 -0.194 -4.25  -2.995  1.743  1.51  -4.352]
 [-4.576 -0.002    nan -2.135 -3.726  3.978 -2.862  5.096  1.817 -0.605]
 [ 1.93  -1.951 -1.803 -4.892 -1.524  2.718 -2.995 -1.52  -3.698  3.758]]


array([4.042, 3.758])

array([2, 9], dtype=int64)

In [4]:
#21강
import pandas as pd
data = {'name' :['kim', 'lee', 'park', 'bang', 'choi'],\
       'score':[100, 95, 90, 85, 75],\
       'grade' :['A', 'A', 'B', 'B', 'C']}
df = pd.DataFrame(data)
df
df['score'].mean()
def pf(x):
    if x == 'C':
        return 'Fail'
    else:
        return "Pass"
df['score'].apply(pf)

name  score grade
0   kim    100     A
1   lee     95     A
2  park     90     B
3  bang     85     B
4  choi     75     C

89.0

0    Pass
1    Pass
2    Pass
3    Pass
4    Pass
Name: score, dtype: object

In [42]:
s1 = pd.Series([1, 2, 3, 4.01, 5.89], index=list('abcde'), dtype=object, name='sr1')
s1
type(s1['a'])
type(s1['e'])

a       1
b       2
c       3
d    4.01
e    5.89
Name: sr1, dtype: object

int

float

In [43]:
ds1 = pd.Series(data=np.arange(1, 5), index=list('abcd'), name='myname')
ds1
ds1.index.name = 'IndexName1'
ds1

a    1
b    2
c    3
d    4
Name: myname, dtype: int32

IndexName1
a    1
b    2
c    3
d    4
Name: myname, dtype: int32

In [45]:
n1 = 'gildong'
ds1 = pd.Series(index=np.arange(1, len(n1) + 1), data = list(n1), name = 'myname')
ds1
ds1.index
ds1.values

1    g
2    i
3    l
4    d
5    o
6    n
7    g
Name: myname, dtype: object

Int64Index([1, 2, 3, 4, 5, 6, 7], dtype='int64')

array(['g', 'i', 'l', 'd', 'o', 'n', 'g'], dtype=object)

In [53]:
sr1 = pd.Series(index = np.arange(1, 6), data = np.random.randint(10, size=(5)))
sr1
s = np.where(sr1.values > 3, sr1.values, 0)
s
s.mean()

1    9
2    6
3    1
4    6
5    9
dtype: int32

array([9, 6, 0, 6, 9])

6.0

In [54]:
sr1 = pd.Series(index = np.arange(1, 6), data = np.random.randint(10, size=(5)))
sr1
sr1[sr1.values > 3].mean()

1    6
2    6
3    1
4    3
5    2
dtype: int32

6.0

In [19]:
#22강
sr1 = pd.Series(index = list('e1d2c3b4a5'), data = np.arange(10))
sr1
sr1.loc['d']
sr1.iloc[2]
sr1.loc[['5']]
sr1.iloc[[9]]
sr1.iloc[2:7:2]
sr1.loc['d':'b':2]

e    0
1    1
d    2
2    3
c    4
3    5
b    6
4    7
a    8
5    9
dtype: int32

2

2

5    9
dtype: int32

5    9
dtype: int32

d    2
c    4
b    6
dtype: int32

d    2
c    4
b    6
dtype: int32

In [29]:
s1 = pd.Series(data=[5, 2, 4, 1, 3], index=list('abcde'))
s1
s1.sort_values()
s1
s1.sort_values(inplace=True)
s1

a    5
b    2
c    4
d    1
e    3
dtype: int64

d    1
b    2
e    3
c    4
a    5
dtype: int64

a    5
b    2
c    4
d    1
e    3
dtype: int64

a    5
b    2
c    4
d    1
e    3
dtype: int64

In [32]:
s1 = pd.Series(data=[5, 2, 4, 1, 3], index=list('cdabe'))
s1
s1.sort_index(inplace=True)
s1

c    5
d    2
a    4
b    1
e    3
dtype: int64

a    4
b    1
c    5
d    2
e    3
dtype: int64

In [46]:
sr1 = pd.Series(data = np.random.randint(10, size=(10)), index = np.arange(10))
sr1
sr2 = sr1 * 3 + 1
sr2
sr2[sr2 % 5 == 0].index
sum(sr2[sr2 % 5 == 0].index)

0    5
1    0
2    3
3    9
4    4
5    7
6    4
7    7
8    3
9    9
dtype: int32

0    16
1     1
2    10
3    28
4    13
5    22
6    13
7    22
8    10
9    28
dtype: int32

Int64Index([2, 8], dtype='int64')

10

In [75]:
sr1 = pd.Series(index = list('abcdef'), data = np.random.randint(100, size = (6)))
sr1
sr1.sort_values(ascending=False, inplace=True)
sr1
sr1.index[1]

a    10
b    76
c    18
d    13
e    21
f    22
dtype: int32

b    76
f    22
e    21
c    18
d    13
a    10
dtype: int32

'f'

In [63]:
sr1 = pd.Series(index = np.random.choice(list('abcdefgh'), size = (5), replace=False), data = np.random.randint(10, size=(5)))
sr1
sr2 = pd.Series(index = np.random.choice(list('abcdefgh'), size = (5), replace=False), data = np.random.randint(10, size=(5)))
sr2
sr3 = pd.Series(index = np.random.choice(list('abcdefgh'), size = (5), replace=False), data = np.random.randint(10, size=(5)))
sr3
sr4 = sr1 + sr2 + sr3
sr4
sr4[sr4.notnull()]
sr4[sr4.notnull()].sum()

g    7
d    0
a    5
f    3
h    6
dtype: int32

a    8
b    3
d    5
h    2
f    3
dtype: int32

e    6
a    8
f    6
g    2
c    6
dtype: int32

a    21.0
b     NaN
c     NaN
d     NaN
e     NaN
f    12.0
g     NaN
h     NaN
dtype: float64

a    21.0
f    12.0
dtype: float64

33.0

In [6]:
#23강
dat = np.arange(12).reshape(3, 4)
df1 = pd.DataFrame(data = dat, index = [1, 2, 3], columns= list('abcd'), dtype = float)
df1
print(df1)

a    b     c     d
1  0.0  1.0   2.0   3.0
2  4.0  5.0   6.0   7.0
3  8.0  9.0  10.0  11.0

     a    b     c     d
1  0.0  1.0   2.0   3.0
2  4.0  5.0   6.0   7.0
3  8.0  9.0  10.0  11.0


In [9]:
df1 = pd.read_table("pandas_data1.txt", sep = '\t', engine = 'python', encoding = 'cp949')
#encoding = 'cp949'없으면 에러발생
df1.head()

이름   성별   학년    중간  기말  출석  과제
0   김둘   여자  1.0   NaN  36   5  75
1   김셋   남자  2.0  17.0  20   5  96
2  김여섯   남자  2.0  28.0  20   4  83
3  김일곱   남자  NaN  20.0  44   6  82
4  김여덜  NaN  1.0  20.0  24   8  88

In [11]:
#DataFrame객체생성1
dat = [['aa', 'suwon', 2], ['bb', 'suwon', 1], ['cc', 'aju', 3]]
df1 = pd.DataFrame(data = dat, index = ['st1', 'st2', 'st3'], columns = ['name', 'univ', 'rank'])
df1
df1['name']

name   univ  rank
st1   aa  suwon     2
st2   bb  suwon     1
st3   cc    aju     3

st1    aa
st2    bb
st3    cc
Name: name, dtype: object

In [14]:
#DataFrame객체생성2
dic1 = {'name' : ['aa', 'bb', 'cc'], 'univ' : ['suwon', 'suwon', 'aju'], 'rank' : [2, 1, 3]}
df1 = pd.DataFrame(dic1, index = ['st1', 'st2', 'st3'])
df1
df1['univ']

name   univ  rank
st1   aa  suwon     2
st2   bb  suwon     1
st3   cc    aju     3

st1    suwon
st2    suwon
st3      aju
Name: univ, dtype: object

In [4]:
import pandas as pd
#DataFrame객체생성4-1
df1 = pd.DataFrame({'name' : ['aa', 'bb', 'cc'], 'univ' : ['suwon', 'suwon', 'aju'], 'rank' : [2, 1, 3]})
df1
df1.to_csv('pandas_data4.txt')

In [23]:
#DataFrame객체생성4-2
df1 = pd.read_csv('pandas_data4.csv', sep = ',', index_col = 'name', engine = 'python', encoding = 'cp949')
df1

Unnamed: 0   univ  rank
name                         
aa             0  suwon     2
bb             1  suwon     1
cc             2    aju     3

In [26]:
#DataFrame객체생성4-3
df1 = pd.read_table('pandas_data4.1.txt', sep = '\t', engine = 'python', encoding = 'cp949')
df1
#Unnamed : 0 행 제거
df1.drop(['Unnamed: 0'], axis = 1, inplace = True)
df1

Unnamed: 0 name   univ  rank
0           0   aa  suwon     2
1           1   bb  suwon     1
2           2   cc    aju     3

name   univ  rank
0   aa  suwon     2
1   bb  suwon     1
2   cc    aju     3

In [28]:
dic1 = {'a' : [1, 2, 3], 'b' : [2, 3, 4], 'c' : [3, 4, 5]}
df1 = pd.DataFrame(dic1, index = ['g', 'k', 'p'])
df1.index
print(df1.index.name)

Index(['g', 'k', 'p'], dtype='object')

None


In [37]:
dic1 = {'a' : [1, 2, 3], 'b' : [2, 3, 4], 'c' : [3, 4, 5]}
df1 = pd.DataFrame(dic1, index = ['g', 'k', 'p'])
df1
df2 = df1
df2.index = ['aa', 'bb', 'cc']
df2.index.name = 'index'
df2.columns.name = 'column'
df2['c'] = df2['c'].astype(float)
df2['b'] = [11.1, 22, 33]
df2

a  b  c
g  1  2  3
k  2  3  4
p  3  4  5

column  a     b    c
index               
aa      1  11.1  3.0
bb      2  22.0  4.0
cc      3  33.0  5.0

In [16]:
#24강
df1 = pd.read_table("pandas_data1.txt", sep="\t", index_col = '이름', engine = 'python', encoding = 'cp949')
df1.loc[:'김열', :]

성별   학년    중간  기말  출석  과제
이름                             
김둘    여자  1.0   NaN  36   5  75
김셋    남자  2.0  17.0  20   5  96
김여섯   남자  2.0  28.0  20   4  83
김일곱   남자  NaN  20.0  44   6  82
김여덜  NaN  1.0  20.0  24   8  88
김아홉   남자  3.0  23.0  45  10  92
김열    남자  3.0  16.0  47   5  83

In [15]:
df1.loc[['최하나'], ['기말']]

기말
이름     
최하나  39

In [18]:
df1.loc['김다섯']#Series
df1.loc[['김다섯']]#DataFrame

성별      남자
학년     2.0
중간    24.0
기말      18
출석       6
과제      84
Name: 김다섯, dtype: object

성별   학년    중간  기말  출석  과제
이름                            
김다섯  남자  2.0  24.0  18   6  84

In [20]:
df1[['학년']].head(7)

학년
이름      
김둘   1.0
김셋   2.0
김여섯  2.0
김일곱  NaN
김여덜  1.0
김아홉  3.0
김열   3.0

In [23]:
df1.loc[['이여섯', '최아홉'], '중간':'출석']

중간  기말  출석
이름               
이여섯  22.0  38   7
최아홉  21.0  33   3

In [22]:
df1[['출석', '과제']].tail(5)

출석  과제
이름         
김다섯   6  84
이하나   5  79
이둘    8  98
이셋    4  79
이넷   10  89

In [26]:
df1 = pd.read_table("pandas_data3.txt", sep="\t", engine = 'python', encoding = 'cp949')
df1.head()

name     gender  year  mid  final  att  proj
kim2               F     1   12     36    5    75
kim3               M     2   17     20    5    96
kim6               M     2   28     20    4    83
kim7               M     2   20     44    6    82
kim8               F     1   20     24    8    88

In [70]:
d1 = df1[df1['final'] > 40]
d1
len(d1) #행
len(list(d1)) #열

name     gender  year  mid  final  att  proj    name
kim7                 M     2   20     44    6    82    kim7
kim9                 M     3   23     45   10    92    kim9
kim10                M     3   16     47    5    83   kim10
lee10                F     4   28     41    9    87   lee10
lee8                 F     4   17     47    5    70    lee8
choi8                M     4   13     48    8    89   choi8
choi10               F     2   16     50   10   100  choi10
lee2                 M     4   30     42    8    98    lee2
lee3                 M     4   22     50    4    79    lee3

9

7

In [75]:
df2 = df1.head()
df2[df2['year'] == 2]

name     gender  year  mid  final  att  proj  name
kim3               M     2   17     20    5    96  kim3
kim6               M     2   28     20    4    83  kim6
kim7               M     2   20     44    6    82  kim7

kim2    kim2
kim3    kim3
kim6    kim6
kim7    kim7
kim8    kim8
Name: name, dtype: object

In [51]:
df2 = df1.loc[df1['att'] <= 5, ['final']]
df2
df2.mean()
np.mean(df2['final'])

final
kim2      36
kim3      20
kim6      20
kim10     47
lee5      35
lee9      36
choi1     39
choi2     29
lee8      47
choi9     33
lee1      17
lee3      50

final    34.083333
dtype: float64

34.083333333333336

In [42]:
df1.loc[df1['proj'] == 100, ['mid', 'final', 'att']]

mid  final  att
choi9    21     33    3
choi10   16     50   10

In [76]:
df1['name'] = df1.index
c1 = df1['att'] >= 5
c2 = df1['proj'] >= 90
df1.loc[c1 & c2, ['name']]

name
kim3      kim3
kim9      kim9
lee5      lee5
park6    park6
choi10  choi10
kim4      kim4
lee2      lee2

In [123]:
df1 = pd.read_table("pandas_data3.txt", sep="\t", engine = 'python', encoding = 'cp949')
df1
df1[['year']]
df1.loc[['lee7']]
len(list(df1))

name     gender  year  mid  final  att  proj
kim2                 F     1   12     36    5    75
kim3                 M     2   17     20    5    96
kim6                 M     2   28     20    4    83
kim7                 M     2   20     44    6    82
kim8                 F     1   20     24    8    88
kim9                 M     3   23     45   10    92
kim10                M     3   16     47    5    83
lee5                 M     3   21     35    5    92
lee9                 M     3   20     36    5    87
lee10                F     4   28     41    9    87
park1                M     4   30     25    7    86
park2                M     4   20     31    7    76
park6                F     1   24     37    7    91
kim1                 F     2   19     18    8    88
park10               M     3   23     20    6    80
choi1                F     1   29     39    5    83
choi2                M     1   18     29    5    86
choi3                M     2   29     39    7    84
lee6                 F     3   22     38    7    78
lee7                 M     3   24     32    8    87
lee8                 F     4   17     47    5    70
choi8                M     4   13     48    8    89
choi9                M     1   21     33    3   100
choi10               F     2   16     50   10   100
kim4                 M     1   18     28    7    93
kim5                 M     2   24     18    6    84
lee1                 M     3   29     17    5    79
lee2                 M     4   30     42    8    98
lee3                 M     4   22     50    4    79
lee4                 F     4   24     21   10    89

year
kim2       1
kim3       2
kim6       2
kim7       2
kim8       1
kim9       3
kim10      3
lee5       3
lee9       3
lee10      4
park1      4
park2      4
park6      1
kim1       2
park10     3
choi1      1
choi2      1
choi3      2
lee6       3
lee7       3
lee8       4
choi8      4
choi9      1
choi10     2
kim4       1
kim5       2
lee1       3
lee2       4
lee3       4
lee4       4

name     gender  year  mid  final  att  proj
lee7               M     3   24     32    8    87

6

In [124]:
df1.drop(['final'], axis=1, inplace=True)
df1

name     gender  year  mid  att  proj
kim2                 F     1   12    5    75
kim3                 M     2   17    5    96
kim6                 M     2   28    4    83
kim7                 M     2   20    6    82
kim8                 F     1   20    8    88
kim9                 M     3   23   10    92
kim10                M     3   16    5    83
lee5                 M     3   21    5    92
lee9                 M     3   20    5    87
lee10                F     4   28    9    87
park1                M     4   30    7    86
park2                M     4   20    7    76
park6                F     1   24    7    91
kim1                 F     2   19    8    88
park10               M     3   23    6    80
choi1                F     1   29    5    83
choi2                M     1   18    5    86
choi3                M     2   29    7    84
lee6                 F     3   22    7    78
lee7                 M     3   24    8    87
lee8                 F     4   17    5    70
choi8                M     4   13    8    89
choi9                M     1   21    3   100
choi10               F     2   16   10   100
kim4                 M     1   18    7    93
kim5                 M     2   24    6    84
lee1                 M     3   29    5    79
lee2                 M     4   30    8    98
lee3                 M     4   22    4    79
lee4                 F     4   24   10    89

In [125]:
df1.loc['new'] = ['F', 2, 22, 6, 80]
df1

name     gender  year  mid  att  proj
kim2                 F     1   12    5    75
kim3                 M     2   17    5    96
kim6                 M     2   28    4    83
kim7                 M     2   20    6    82
kim8                 F     1   20    8    88
kim9                 M     3   23   10    92
kim10                M     3   16    5    83
lee5                 M     3   21    5    92
lee9                 M     3   20    5    87
lee10                F     4   28    9    87
park1                M     4   30    7    86
park2                M     4   20    7    76
park6                F     1   24    7    91
kim1                 F     2   19    8    88
park10               M     3   23    6    80
choi1                F     1   29    5    83
choi2                M     1   18    5    86
choi3                M     2   29    7    84
lee6                 F     3   22    7    78
lee7                 M     3   24    8    87
lee8                 F     4   17    5    70
choi8                M     4   13    8    89
choi9                M     1   21    3   100
choi10               F     2   16   10   100
kim4                 M     1   18    7    93
kim5                 M     2   24    6    84
lee1                 M     3   29    5    79
lee2                 M     4   30    8    98
lee3                 M     4   22    4    79
lee4                 F     4   24   10    89
new                  F     2   22    6    80

In [126]:
df1.loc[['lee7']]
df1.drop(['lee7', 'kim1'], axis = 0, inplace=True)
c1 = df1['year'] == 1 
c2 = df1['year'] == 2
df1['rank'] = np.where(c1 | c2, 'L', 'H')
df1

name     gender  year  mid  att  proj
lee7               M     3   24    8    87

name     gender  year  mid  att  proj rank
kim2                 F     1   12    5    75    L
kim3                 M     2   17    5    96    L
kim6                 M     2   28    4    83    L
kim7                 M     2   20    6    82    L
kim8                 F     1   20    8    88    L
kim9                 M     3   23   10    92    H
kim10                M     3   16    5    83    H
lee5                 M     3   21    5    92    H
lee9                 M     3   20    5    87    H
lee10                F     4   28    9    87    H
park1                M     4   30    7    86    H
park2                M     4   20    7    76    H
park6                F     1   24    7    91    L
park10               M     3   23    6    80    H
choi1                F     1   29    5    83    L
choi2                M     1   18    5    86    L
choi3                M     2   29    7    84    L
lee6                 F     3   22    7    78    H
lee8                 F     4   17    5    70    H
choi8                M     4   13    8    89    H
choi9                M     1   21    3   100    L
choi10               F     2   16   10   100    L
kim4                 M     1   18    7    93    L
kim5                 M     2   24    6    84    L
lee1                 M     3   29    5    79    H
lee2                 M     4   30    8    98    H
lee3                 M     4   22    4    79    H
lee4                 F     4   24   10    89    H
new                  F     2   22    6    80    L